In [1]:
# Data manipulation
import pandas as pd
import numpy as np

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Machine learning
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv("../data/ds_salaries.csv")
df.head()

,Unnamed: 0,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,0,2020,MI,FT,Data Scientist,70000,EUR,79833,DE,0,DE,L
1,1,2020,SE,FT,Machine Learning Scientist,260000,USD,260000,JP,0,JP,S
2,2,2020,SE,FT,Big Data Engineer,85000,GBP,109024,GB,50,GB,M
3,3,2020,MI,FT,Product Data Analyst,20000,USD,20000,HN,0,HN,S
4,4,2020,SE,FT,Machine Learning Engineer,150000,USD,150000,US,50,US,L

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 607 entries, 0 to 606
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Unnamed: 0          607 non-null    int64
 1   work_year           607 non-null    int64
 2   experience_level    607 non-null    object
 3   employment_type     607 non-null    object
 4   job_title           607 non-null    object
 5   salary              607 non-null    int64
 6   salary_currency     607 non-null    object
 7   salary_in_usd       607 non-null    int64
 8   employee_residence  607 non-null    object
 9   remote_ratio        607 non-null    int64
 10  company_location    607 non-null    object
 11  company_size        607 non-null    object
dtypes: int64(5), object(7)
memory usage: 57.0+ KB

In [4]:
df.describe()

       Unnamed: 0    work_year        salary  salary_in_usd  remote_ratio
count  607.000000   607.000000  6.070000e+02     607.000000     607.00000
mean   303.000000  2021.405272  3.240001e+05  112297.869852      70.92257
std    175.370085     0.692133  1.544357e+06   70957.259411      40.70913
min      0.000000  2020.000000  4.000000e+03    2859.000000       0.00000
25%    151.500000  2021.000000  7.000000e+04   62726.000000      50.00000
50%    303.000000  2022.000000  1.150000e+05  101570.000000     100.00000
75%    454.500000  2022.000000  1.650000e+05  150000.000000     100.00000
max    606.000000  2022.000000  3.040000e+07  600000.000000     100.00000

In [5]:
df = df.drop(["Unnamed: 0"], axis = 1)

In [6]:
df.head()

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2020,MI,FT,Data Scientist,70000,EUR,79833,DE,0,DE,L
1,2020,SE,FT,Machine Learning Scientist,260000,USD,260000,JP,0,JP,S
2,2020,SE,FT,Big Data Engineer,85000,GBP,109024,GB,50,GB,M
3,2020,MI,FT,Product Data Analyst,20000,USD,20000,HN,0,HN,S
4,2020,SE,FT,Machine Learning Engineer,150000,USD,150000,US,50,US,L

In [7]:
df = df.drop(columns=["salary", "salary_currency"])

In [8]:
df.head()

,work_year,experience_level,employment_type,job_title,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2020,MI,FT,Data Scientist,79833,DE,0,DE,L
1,2020,SE,FT,Machine Learning Scientist,260000,JP,0,JP,S
2,2020,SE,FT,Big Data Engineer,109024,GB,50,GB,M
3,2020,MI,FT,Product Data Analyst,20000,HN,0,HN,S
4,2020,SE,FT,Machine Learning Engineer,150000,US,50,US,L

In [9]:
country_counts = df["employee_residence"].value_counts()

major_countries = country_counts[country_counts >= 10].index

major_countries

Index(['US', 'GB', 'IN', 'CA', 'DE', 'FR', 'ES', 'GR'], dtype='object', name='employee_residence')

In [10]:
df["residence_grouped"] = df["employee_residence"].apply(
    lambda x: x if x in major_countries else "Other"
)

df["residence_grouped"].value_counts()

residence_grouped
US       332
Other    101
GB        44
IN        30
CA        29
DE        25
FR        18
ES        15
GR        13
Name: count, dtype: int64

In [11]:
df = df.drop(["employee_residence"], axis=1)
df.head()

,work_year,experience_level,employment_type,job_title,salary_in_usd,remote_ratio,company_location,company_size,residence_grouped
0,2020,MI,FT,Data Scientist,79833,0,DE,L,DE
1,2020,SE,FT,Machine Learning Scientist,260000,0,JP,S,Other
2,2020,SE,FT,Big Data Engineer,109024,50,GB,M,GB
3,2020,MI,FT,Product Data Analyst,20000,0,HN,S,Other
4,2020,SE,FT,Machine Learning Engineer,150000,50,US,L,US

In [12]:
df = df.drop(["company_location"], axis=1)
df.head(10)

,work_year,experience_level,employment_type,job_title,salary_in_usd,remote_ratio,company_size,residence_grouped
0,2020,MI,FT,Data Scientist,79833,0,L,DE
1,2020,SE,FT,Machine Learning Scientist,260000,0,S,Other
2,2020,SE,FT,Big Data Engineer,109024,50,M,GB
3,2020,MI,FT,Product Data Analyst,20000,0,S,Other
4,2020,SE,FT,Machine Learning Engineer,150000,50,L,US
5,2020,EN,FT,Data Analyst,72000,100,L,US
6,2020,SE,FT,Lead Data Scientist,190000,100,S,US
7,2020,MI,FT,Data Scientist,35735,50,L,Other
8,2020,MI,FT,Business Data Analyst,135000,100,L,US
9,2020,SE,FT,Lead Data Engineer,125000,50,S,Other

In [13]:
df = df.drop(["job_title"], axis=1)
df.head(10)

,work_year,experience_level,employment_type,salary_in_usd,remote_ratio,company_size,residence_grouped
0,2020,MI,FT,79833,0,L,DE
1,2020,SE,FT,260000,0,S,Other
2,2020,SE,FT,109024,50,M,GB
3,2020,MI,FT,20000,0,S,Other
4,2020,SE,FT,150000,50,L,US
5,2020,EN,FT,72000,100,L,US
6,2020,SE,FT,190000,100,S,US
7,2020,MI,FT,35735,50,L,Other
8,2020,MI,FT,135000,100,L,US
9,2020,SE,FT,125000,50,S,Other

In [14]:
X = df.drop("salary_in_usd", axis = 1)
y = df["salary_in_usd"]

X.head()

,work_year,experience_level,employment_type,remote_ratio,company_size,residence_grouped
0,2020,MI,FT,0,L,DE
1,2020,SE,FT,0,S,Other
2,2020,SE,FT,50,M,GB
3,2020,MI,FT,0,S,Other
4,2020,SE,FT,50,L,US

In [15]:
# Never preprocess before splitting as it can cause data leakage
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size = 0.2,
    random_state = 42
)

In [16]:
X_train.shape, X_test.shape

((485, 6), (122, 6))

In [17]:
numerical_cols = list(X_train.select_dtypes(include=["int64", "float64"]).columns)
categorical_cols = list(X_train.select_dtypes(include=["object"]).columns)

numerical_cols, categorical_cols

(['work_year', 'remote_ratio'],
 ['experience_level', 'employment_type', 'company_size', 'residence_grouped'])

In [18]:
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer

In [19]:
preprocessor = ColumnTransformer( #Allows us to apply different preprocessing to different column groups.
    transformers=[
        ("num", StandardScaler(), numerical_cols), 
        # "num" → name of transformation
        # StandardScaler() → scales numerical features (mean=0, std=1)
        # numerical_cols → columns to apply it to
        ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_cols) 
        # OneHotEncoder → converts categories into binary columns
        #handle_unknown="ignore" → prevents errors if test data contains unseen categories
    ]
)

In [20]:
from sklearn.pipeline import Pipeline #Pipeline chains preprocessing and model together into one object.
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

In [21]:
model = Pipeline( #Creates sequential workflow.
    steps = [
        ("preprocessing", preprocessor), # first step: Apply ColumnTransformer (scaling + encoding).
        ("regressor", LinearRegression()) # second step: Train Linear Regression on transformed data.
    ]
) # The model will never see raw text columns.

In [22]:
model.fit(X_train, y_train) # Applies preprocessing to training data then Fits Linear Regression and Learns coefficients

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['work_year',
                                                   'remote_ratio']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['experience_level',
                                                   'employment_type',
                                                   'company_size',
                                                   'residence_grouped'])])),
                ('regressor', LinearRegression())])

In [23]:
y_pred = model.predict(X_test) # Produces predicted salaries

In [24]:
mse = mean_squared_error(y_test, y_pred) # Computes average squared error
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred) # Returns R² score: 1 → perfect; 0 → predicts mean only, Negative → worse than predicting mean

rmse, r2

(np.float64(42069.20732231801), 0.5382162400241409)

In [25]:
# Is it underfitting or overfitting?
y_train_pred = model.predict(X_train)

train_rmse = np.sqrt(mean_squared_error(y_train, y_train_pred))
train_r2 = r2_score(y_train, y_train_pred)

train_rmse, train_r2

(np.float64(53375.579766827424), 0.4634577457284713)

In [26]:
# ===Observation===
# test: RMSE of 58818.7834 and r2 of 9.7% indicate Linear regression is performing poorly on the test dataset.
# train: RMSE of 39274 and r2 of 71% indicate the model is overfitting as it performs better on training data than on test data.
''' 
Why is linear regression overfitting?
Sounds counterintuitive given the simplicity of the model.
However we applied OneHotEncoding to: 
    job_title
    employee_residence
    company_location
That likely created hundreds of dummy variables.

Linear Regression:
-Has no built-in regularization
-Will try to fit every coefficient
-Especially dangerous with many sparse columns

So it memorized patterns in training data.

+The likely culprit+
Most likely:
-job_title
-employee_residence
-company_location

High-cardinality categorical features.

===+++Now We Upgrade the Model+++===
Instead of removing features blindly, we switch to:
🌲 Random Forest Regressor

Why?
-Handles non-linear relationships
-Robust to high dimensional sparse features
-Less sensitive to multicollinearity
-Naturally handles interactions
'''

' \nWhy is linear regression overfitting?\nSounds counterintuitive given the simplicity of the model.\nHowever we applied OneHotEncoding to: \n    job_title\n    employee_residence\n    company_location\nThat likely created hundreds of dummy variables.\n\nLinear Regression:\n-Has no built-in regularization\n-Will try to fit every coefficient\n-Especially dangerous with many sparse columns\n\nSo it memorized patterns in training data.\n\n+The likely culprit+\nMost likely:\n-job_title\n-employee_residence\n-company_location\n\nHigh-cardinality categorical features.\n\n===+++Now We Upgrade the Model+++===\nInstead of removing features blindly, we switch to:\n🌲 Random Forest Regressor\n\nWhy?\n-Handles non-linear relationships\n-Robust to high dimensional sparse features\n-Less sensitive to multicollinearity\n-Naturally handles interactions\n'

In [27]:
from sklearn.ensemble import RandomForestRegressor as rfr

In [28]:
rf_model = Pipeline(
    steps = [
        ("preprocessing", preprocessor),
        ("regressor", rfr( # Creates an ensemble of decision trees.
            n_estimators=100, # Number of trees in the forest. More trees → better stability (but slower).
            random_state=42 # Ensures reproducibility.
        ))
    ]
)

In [29]:
rf_model.fit(X_train, y_train)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['work_year',
                                                   'remote_ratio']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['experience_level',
                                                   'employment_type',
                                                   'company_size',
                                                   'residence_grouped'])])),
                ('regressor', RandomForestRegressor(random_state=42))])

In [30]:
rf_pred = rf_model.predict(X_test)

rf_rmse = np.sqrt(mean_squared_error(y_test, rf_pred))
rf_r2 = r2_score(y_test, rf_pred)

rf_rmse, rf_r2

(np.float64(45738.336604147466), 0.4541532484009315)

In [31]:
# ==+Observation+==
'''
Random Forest:
-Captured non-linear relationships
-Handled high-cardinality categorical variables better
-Reduced generalization error significantly
Now we must ask the professional question:
*Is Random Forest still overfitting?

We only evaluated test performance.

Let’s check training performance.
'''

'\nRandom Forest:\n-Captured non-linear relationships\n-Handled high-cardinality categorical variables better\n-Reduced generalization error significantly\nNow we must ask the professional question:\n*Is Random Forest still overfitting?\n\nWe only evaluated test performance.\n\nLet’s check training performance.\n'

In [32]:
rf_train_pred = rf_model.predict(X_train)

rf_train_rmse = np.sqrt(mean_squared_error(y_train, rf_train_pred))
rf_train_r2 = r2_score(y_train, y_train_pred)

rf_train_rmse, rf_train_r2

(np.float64(43708.13348561247), 0.4634577457284713)

In [33]:
# ==+ Observation +==
'''
Train RMSE ≈ 30,159
Train R² ≈ 0.709

Test RMSE ≈ 42,303
Test R² ≈ 0.533

📊 Overfitting Analysis
Train R² = 0.71
Test R² = 0.53

Gap ≈ 0.18

That is:
👉 Mild to moderate overfitting
👉 Totally acceptable for a first untuned Random Forest

This is normal.

🎯 Interpretation
Random Forest:
-Generalizes much better than Linear Regression
-Still slightly overfits
-Has reduced test error by ~16,500 USD
-Explains 53% of salary variance

For a real-world noisy salary dataset?

That’s actually solid.
'''
# Now we improve the model.
'''
We need to answer: Is job_title actually helping?

Random Forest gives us feature importance.
'''

'\nWe need to answer: Is job_title actually helping?\n\nRandom Forest gives us feature importance.\n'

In [34]:
# Get feaure names after preprocessing
feature_names = rf_model.named_steps["preprocessing"].get_feature_names_out()

# Get importance values
importances = rf_model.named_steps["regressor"].feature_importances_

# create a dataframe
feature_importance_df = pd.DataFrame({
    "feature": feature_names,
    "importance": importances
}).sort_values(by="importance", ascending=False)

feature_importance_df.head(10)

                      feature  importance
21  cat__residence_grouped_US    0.439401
3    cat__experience_level_EX    0.110240
0              num__work_year    0.096286
1           num__remote_ratio    0.079019
10        cat__company_size_L    0.048599
5    cat__experience_level_SE    0.048146
2    cat__experience_level_EN    0.037478
11        cat__company_size_M    0.029484
4    cat__experience_level_MI    0.021875
12        cat__company_size_S    0.021038

In [35]:
# ==+ Observation +==
'''
Top Feature is: cat__employee_residence_US → 0.3465
That means:
*Whether someone resides in the US explains ~34.6% of the model’s decision power.
That is massive.

🧠 Interpretation

This tells us something important about the dataset:

💰 Salaries are heavily geography-driven.

If you're in the US → salary distribution shifts upward dramatically.

This makes sense economically.

🎯 Second Observation

Experience levels are important:
-experience_level_EX
-experience_level_SE
-experience_level_EN

This is good — it means the model is learning seniority patterns.

🚨 Third Observation — Job Titles

Several specific job titles appear in top 10:
-Principal Data Engineer
-Data Analyst
-Applied ML Scientist
-Research Scientist

This confirms:
👉 job_title is highly predictive
👉 But very granular
👉 Risk of memorization still exists
'''
# 🔥 Critical Thinking Question
'''
If employee_residence_US has 0.34 importance…

What might happen if we deploy this model and:

-Someone from Kenya inputs data?
-Or a country with only 1–2 entries in the dataset?

Think about that.

🚀 Next Professional Move

We improve generalization.
There are 3 smart paths:
Option A — Hyperparameter Tuning
Reduce overfitting:
-max_depth
-min_samples_split
-min_samples_leaf

Option B — Feature Engineering
-Group rare job titles
-Extract seniority from job title
-Group countries into regions

Option C — Try Gradient Boosting (Often performs better than RF)
'''
# Before feature engineering, tune hyperparameters

'\nIf employee_residence_US has 0.34 importance…\n\nWhat might happen if we deploy this model and:\n\n-Someone from Kenya inputs data?\n-Or a country with only 1–2 entries in the dataset?\n\nThink about that.\n\n🚀 Next Professional Move\n\nWe improve generalization.\nThere are 3 smart paths:\nOption A — Hyperparameter Tuning\nReduce overfitting:\n-max_depth\n-min_samples_split\n-min_samples_leaf\n\nOption B — Feature Engineering\n-Group rare job titles\n-Extract seniority from job title\n-Group countries into regions\n\nOption C — Try Gradient Boosting (Often performs better than RF)\n'

In [36]:
rf_model_tuned = Pipeline(
    steps=[
        ("preprocessing", preprocessor),
        ("regressor", rfr(
            n_estimators = 300, # more trees for stability
            max_depth = 15, # prevents trees from growing too deep
            min_samples_split = 5, # requires more data to split
            min_samples_leaf = 2, # prevents leaves with single samples
            random_state = 42
        ))
    ]
)

In [37]:
rf_model_tuned.fit(X_train, y_train)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['work_year',
                                                   'remote_ratio']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['experience_level',
                                                   'employment_type',
                                                   'company_size',
                                                   'residence_grouped'])])),
                ('regressor',
                 RandomForestRegressor(max_depth=15, min_samples_leaf=2,
                                       min_samples_split=5, n_estimators=300,
                                       random_state=42))])

In [38]:
rf_tuned_pred = rf_model_tuned.predict(X_test)

rf_tuned_rmse = np.sqrt(mean_squared_error(y_test, rf_tuned_pred))
rf_tuned_r2 = r2_score(y_test, rf_tuned_pred)

rf_tuned_rmse, rf_tuned_r2

(np.float64(44610.094112635416), 0.4807502734981012)

In [39]:
rf_tuned_train_pred = rf_model_tuned.predict(X_train)

rf_tuned_train_rmse = np.sqrt(mean_squared_error(y_train, rf_tuned_train_pred))
rf_tuned_train_r2 = r2_score(y_train, rf_tuned_train_pred)

rf_tuned_train_rmse, rf_tuned_train_r2

(np.float64(46221.34663275267), 0.597650091072323)

In [40]:
# seems the < 10 error and > 80 r2 will be impossible given the dataset. If dataset was richer then maybe it would be less far-fetched.

In [41]:
from sklearn.model_selection import cross_val_score

cv_scores = cross_val_score(
    rf_model_tuned,
    X,
    y,
    cv=5,
    scoring="r2"
)

cv_scores.mean(), cv_scores.std()

(np.float64(0.35326927697485655), np.float64(0.10628165534510983))

In [42]:
import joblib

joblib.dump(rf_model_tuned, "salary_model.pkl")

['salary_model.pkl']

In [43]:
loaded_model = joblib.load("salary_model.pkl")

loaded_model.predict(X.iloc[:5])

array([ 80479.44822182, 123262.69971693,  93017.69097751,  33658.13215212,
       164440.05638599])

In [44]:
X.head()

,work_year,experience_level,employment_type,remote_ratio,company_size,residence_grouped
0,2020,MI,FT,0,L,DE
1,2020,SE,FT,0,S,Other
2,2020,SE,FT,50,M,GB
3,2020,MI,FT,0,S,Other
4,2020,SE,FT,50,L,US